### ISSUE TITLE
Member verification email error when sending bulk

### ISSUE THREAD

**Issue by vegarandi** [WebDevStudios/BuddyPress-Registration-Options#151] opened 2018-01-25 14:35 UTC
Hello!

When I Confim more than one user a a time. 
User name gets inserted in the email wrong. 
Either everyone gets it with he same username or it is shifted somehow. But that do not get their emails with their usename. 

Could you please check that? 

Thank you.

**Comment by tw2113** [comment] 2018-01-25 17:44
This is with the user meta/user data in the wp_user* tables, correct? Haven't seen behavior like this previously, but I also haven't found reason to double check those spots either, so I'll need to try and confirm myself.

**Comment by tw2113** [comment] 2018-01-27 01:03
Not managing to recreate. I registered 2 new users each with distinct usernames/passwords, and when I approved both at the same time, their data was still matching like expected.

Can you provide some screenshots of what you're seeing and clarify what you're expecting to see if things were working as intended? It may help me visualize what's going on.

For what it's worth, all of the parts that our plugin does is well after the creation of the user in the database, we don't hinder that process at all, we act on some processes executed after.

**Comment by tw2113** [comment] 2018-04-03 00:33
Closing as this will be addressed in version 4.3.4 and I had since been able to recreate.

**Closed by tw2113** 2018-04-03 00:33 UTC
