### ISSUE TITLE
Cannot logout!

### ISSUE THREAD

**Issue by antonality** [WebDevStudios/BuddyPress-Registration-Options#136] opened 2017-01-09 21:28 UTC
I'm using BP Registration Options version 4.3.1 with my Wordpress website using BuddyPress. When I select the option "Only registered or approved members can view BuddyPress/bbPress pages (Private Network)," I am unable to log out of my WP account. My website would also then be rendered inaccessible.

I would want to select this option, as unregistered members are able to see some of the pages they're not supposed to see.

Thanks!

**Comment by tw2113** [comment] 2017-01-09 21:37
The plugin shouldn't be doing anything directly to prevent logging out. However, a couple cases I can think of that could be contributing to this are as follows:

The entire site is buddypress only, meaning there's no non-buddypress areas like a blog section, or an ecommerce store, or standard pages etc.

The areas that are accessible in the example case you outline, don't have any presented logout links in the browser window, or no admin bar present that would also offer a logout link.out.

That's the only way I can think of that the issue would be present.

**Comment by antonality** [comment] 2017-01-09 22:14
Yes you're right, the entire site is BuddyPress only. But I have two options of logging out, one a buddypress logout button created by a widget in the left sidebar, and the other a menu button in the main menu from the main WordPress menu options.

I tried removing them one at a time, but the problem persisted.

What could I have been doing wrong? I don't understand what you meant by "logout links."

**Comment by tw2113** [comment] 2017-01-10 02:34
What I meant by "logout links" is pretty much what you described above. The button in the widget, and a menu button. You have UI elements present that people can click on that are meant to log them out of the website.

That said, I'm not sure what would be preventing success in logging out at this point, because like I said earlier, we don't do anything in regards to the login/logout process. Pending members simply have some user meta set for their user that we use to check if they're still pending or not, and restrict them to their frontend user profile, if private network is enabled. If they just need to be moderated, then they're able to navigate the BuddyPress/bbPress areas, but we do our best to hide the UI they'd use to participate in anything. Essentially a "read only".

Have you confirmed the ability to log out successfully returns when BuddyPress Registration Options is disabled? or is it still present at that point? I'm assuming at least one of the two mentioned logout buttons is present when one is viewing their user profile.

**Comment by antonality** [comment] 2017-01-10 03:17
I can log out when the option _"Only registered or approved members can view BuddyPress/bbPress pages (Private Network)"_ is unselected. When I do, the logout link in the sidebar turns into a login link, and the main menu logout button disappears. But at that time, when I'm not the admin anymore, I can see the activity page, both left and right sidebars and even the members widget. However all that remains in the main menu are two buttons: a log in button and a register button.

When the option _"Only registered or approved members can view BuddyPress/bbPress pages (Private Network)"_ is selected, however, I can't logout. And then my website becomes unavailable with the error page:

**The mydomain.com page isn’t working

mydomain.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS**

Then I have to login to my wp admin area and the site is back again.

What use is the option I mentioned earlier if it can't be used anyway? Do I have to make my site a "Private Network," and if I should, how do I do it?

**Comment by tw2113** [comment] 2017-01-10 03:39
Ahhhh, this is good information to know, and wasn't presented at first. To be fair, some details slipped my mind as well. This means it's not a logout issue, it's a template_redirect issue that we use with the plugin.

The issue is going to stem from https://github.com/WebDevStudios/BuddyPress-Registration-Options/blob/master/includes/core.php#L343-L424 specifically line 373 to 392. We try to keep the logged out users away completely for the social areas, and send them to the homepage. However, in your case, the homepage is still BuddyPress, thus the too many redirects error you're encountering.

So, to clarify, chances are you ARE logging out, like I was pointing out earlier, BUT the infinite loop is a big issue and renders the site inaccessible. It's going to be an interesting corner to be in, because of the whole site being BuddyPress, but you wanting to keep things rather limited.

That said, this filter is probably going to be your best bet: https://github.com/WebDevStudios/BuddyPress-Registration-Options/blob/master/includes/core.php#L460-L487. If the bp_registration_buddypress_allowed_areas() function ultimately returns true, then we exit out of the template_redirect callback, and don't do any redirecting. I think doing some sort of URL check or perhaps is_front_page() check to see if you're on https://www.domain.com/, then return true, and wherever else you may see fit. Otherwise, return the originally passed in value, for consistency with other checks that may have validated or not.

That would allow a logged out to at least see the landing page, but not navigate anywhere else.

Closing the GitHub issue itself, but we can still comment/talk afterwards as necessary.

**Closed by tw2113** 2017-01-10 03:39 UTC

**Comment by antonality** [comment] 2017-01-10 03:56
When I update the file from Editor after copying the entire contents from the filter link you sent, this error message comes up:

Parse error: syntax error, unexpected 'GitHub' (T_STRING) in /home/pilipian/public_html/tajanlangit.com/wp-content/plugins/bp-registration-options/includes/core.php on line 696

When I paste back the original file that I copied into a TextEdit document, and update the file again, the same Parse error occurs again.

What should I do?

**Comment by tw2113** [comment] 2017-01-10 04:33
What file are you editing, and what exactly are you copy/pasting?

You'd ideally want to put your filtering in your theme's functions.php file. 

Perhaps something like this:

```
function antonality_filter_bpro_allowed_areas( $is_allowed ) {
    // Checks if is front page, and if so, sets $is_allowed to true.
    if ( is_front_page() ) {
        $is_allowed = true;
    }
    // If the is_front_page check above doesn't set this to true, then this will still be the original passed in value. 
    return $is_allowed;
}
add_filter( 'bprwg_buddypress_allowed_areas', 'antonality_filter_bpro_allowed_areas' );
```

**Comment by antonality** [comment] 2017-01-10 04:42
Uh-oh, I went here:

Editing bp-registration-options/includes/core.php (active)

and copy-pasted the entire contents of https://github.com/WebDevStudios/BuddyPress-Registration-Options/blob/master/includes/core.php#L460-L487 into it.

However before I did this, I copied the original contents of the file to a text editor. When the error came up with your file, I just deleted the contents from your link and re-inserted the original contents. But then the same Parse error happened, and now I can't access my website anymore...

Sorry, I'm still learning...

**Comment by tw2113** [comment] 2017-01-10 04:50
You'll likely need to log into the server via FTP and edit the file that way, for the sake of getting the site back up.

Either re-upload the plugin that way, or at least upload a restored copy of core.php. You can copy/paste all of https://raw.githubusercontent.com/WebDevStudios/BuddyPress-Registration-Options/master/includes/core.php, after selecting all of it via cmd+a/ctrl+a (not sure if on mac or PC), and save the file before uploading.

**Comment by antonality** [comment] 2017-01-10 05:00
I can't even log in into my wp-admin account now. It's the same parse error message:

Parse error: syntax error, unexpected 'GitHub' (T_STRING) in /home/pilipian/public_html/tajanlangit.com/wp-content/plugins/bp-registration-options/includes/core.php on line 696

My bad.
